# Generated by Django 4.1.5 on 2023-02-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todouser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
