# Generated by Django 4.1.5 on 2023-02-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_todouser_created_todouser_groups_todouser_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todouser',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='todouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
